"""
Django settings for teachflow project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _get_bool_env(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


def _get_list_env(name: str, default: list[str]) -> list[str]:
    value = os.environ.get(name)
    if not value:
        return default
    return [item.strip() for item in value.split(",") if item.strip()]


# SECURITY WARNING: don't run with debug turned on in production!
#
# Defaults to False so that a deploy which forgets DJANGO_DEBUG fails closed
# rather than publishing tracebacks to the open internet (Article 9). Local
# development must therefore set DJANGO_DEBUG=1 -- see .env.example and the
# "Local development" section of DEPLOYMENT.md.
DEBUG = _get_bool_env("DJANGO_DEBUG", False)

# Debug mode is the single input that turns off everything below: tracebacks go
# public, secure cookies and HSTS are skipped, the SSL redirect is skipped, and
# the secret key falls back to a throwaway. Failing closed on a *missing*
# variable is not enough on its own, because the documented remedy for a
# missing key would otherwise be "turn debug on" -- which is exactly the wrong
# move on a server, and one that leaves the site looking perfectly healthy.
#
# So: refuse to start with debug on anywhere that advertises itself as hosted.
_HOSTING_MARKERS = (
    "WEBSITE_HOSTNAME",  # Azure App Service
    "WEBSITE_SITE_NAME",  # Azure App Service
    "DYNO",  # Heroku
    "K_SERVICE",  # Cloud Run
)

if DEBUG:
    _hosted_by = next((m for m in _HOSTING_MARKERS if os.environ.get(m)), None)
    if _hosted_by:
        raise ImproperlyConfigured(
            "DJANGO_DEBUG is enabled but {} is set, so this is a hosted "
            "environment. Debug mode here would publish tracebacks, disable "
            "secure cookies and HSTS, and sign every visitor's session with a "
            "throwaway key. Unset DJANGO_DEBUG and set DJANGO_SECRET_KEY "
            "instead.".format(_hosted_by)
        )

# SECURITY WARNING: keep the secret key used in production secret!
#
# Outside DEBUG this is required. Inside DEBUG a fresh random key is generated
# per process rather than read from a literal in this file: a committed key is
# one that signs real visitors' session cookies the moment debug mode reaches a
# server by accident, and it is readable by anyone with the repository. The
# cost of generating one is that local sessions do not survive a restart, which
# is the right amount of inconvenient.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY is not set and has no default outside DEBUG. "
            "Set it in the environment. Do NOT set DJANGO_DEBUG=1 to work "
            "around this on a server -- see the comment above."
        )
    SECRET_KEY = get_random_secret_key()

ALLOWED_HOSTS = _get_list_env("DJANGO_ALLOWED_HOSTS", ["localhost", "127.0.0.1"])

# Needed when deploying over HTTPS on a real domain.
CSRF_TRUSTED_ORIGINS = _get_list_env("DJANGO_CSRF_TRUSTED_ORIGINS", [])

# --- Sessions ---------------------------------------------------------------
#
# The flow's session holds the visitor's own answers (see the data
# classification section of CLAUDE.md), so it is deliberately short-lived.
# Django's defaults -- two weeks, surviving a browser close -- would keep a
# record of someone's right-to-work and qualification answers on the server
# long after they had finished with it, for no benefit to them.
#
# The session is written on most requests, which re-bases the expiry, so this
# behaves as an hour of inactivity rather than an hour in total.
SESSION_COOKIE_AGE = 3600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Expired rows are NOT removed automatically. `manage.py clearsessions` must run
# on a schedule or django_session accumulates for the life of the deployment --
# see DEPLOYMENT.md.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'flow'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'teachflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'teachflow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}


# Production security settings
if not DEBUG:
    SECURE_SSL_REDIRECT = _get_bool_env("DJANGO_SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
